### ISSUE TITLE
Getting started....

### ISSUE THREAD

**Issue by drelight** [drelight/Crime-Rates-in-B.City#1]
Trying to get something working before I keep building on this, but right off the bat I'm getting
` ImportError Missing required dependencies ['numpy']`

Pandas and Numpy is installed on my local machine -- do I need to install through the Github repo?

Very possible I just don't know what I'm doing :-)

**Comment by patrickgr80** [comment]
Is pandas installed in your current local environment?

**Comment by drelight** [comment]
Made a new clone and it worked that time. Not sure what happened but good to go.
